### ISSUE TITLE
Format of a minimal configuration file is not clear

### ISSUE THREAD

**Issue by livenson** [NBISweden/LocalEGA#117]
Hi,

I'm experimenting with localEGA setup using docker and a bit stuck at what kind of file is expected for conf.ini. Like what would a minimal file be? Could you please provide an example?

thanks!

**Comment by dtitov** [comment]
I'm still confused about the content of this file, but you can grab `/src/lega/conf/defaults.ini` as an example and replace default params with your own.

**Comment by nanjiangshu** [comment]
I have updated the instruction for how to set up the docker version of LocalEGA. Some examples are added. Please find it at  https://github.com/NBISweden/LocalEGA/tree/doc/docker-compose
