### ISSUE TITLE
Implement User Authentication tests

### ISSUE THREAD

**Issue by dtitov** [NBISweden/LocalEGA#175]
Based on: https://github.com/NBISweden/LocalEGA/wiki/Testing-LocalEGA
- [x] (U.1) User does not exist
- [x] (U.2) User does not have rights to access this LocalEGA instance because he's a user of another LocalEGA instance
- [x] (U.3) User account has expired
- [x] (U.4) User authentication failed: password or ssh-key
- [x] (U.5) User authentication succeeds but user inbox not created: ssh/sftp access denied
- [x] (U.6) Database connection fails, so user information is not available

**Comment by jhagberg** [comment]
Update U6 test during Sprint 18

**Comment by dtitov** [comment]
Finished.
