### ISSUE TITLE
[BUG] making images exits with error if the common image does not exist

### ISSUE THREAD

**Issue by nanjiangshu** [NBISweden/LocalEGA#177]
If the image  `nbisweden/ega-common:latest`, make will not work. We need to check the existence of the image before running `docker rmi`

**Comment by silverdaz** [comment]
Did you actually try it, or you just read the code?
The makefile contains a tiny `-` sign in front of that line.
That takes care of the situation you're mentioning.
So, can I close the issue, or you prefer to do it?

**Comment by nanjiangshu** [comment]
Which branch do you mean?  I tried and not working if there is no images at the beginning.
There is no `-` sign at https://github.com/NBISweden/LocalEGA/blob/dev/docker/images/Makefile#L22
