### ISSUE TITLE
Move entrypoint scripts inside to Dockerfiles 

### ISSUE THREAD

**Issue by juhtornr** [NBISweden/LocalEGA#183]
Currently Docker containers depends on external entrypoint scripts which are in mounted volumes. The best practise would be to have “self contained” containers so that they would not be dependent on anything external (or at least we should minimise the dependencies).

For this reason we should move entrypoint scripts inside to the containers.

**Comment by silverdaz** [comment]
The problem is `pip install <source-code>` could not be included in the image, since it still changes.

However, since we now re-create the images (and cache them), it is now doable.
