### ISSUE TITLE
Keep track of CSC server hardware and software installation process

### ISSUE THREAD

**Issue by andersla** [NBISweden/LocalEGA#20]
Keep track of CSC server hardware and software installation process

**Comment by jaakkocsc** [comment]
Two servers acquired:
- Dell R430, 2 CPUs, RAM 128GB, Local storage 4* 4 TB NL-SAS, Network. 2 x 10Gbit/s
- Dell R630, 2 x 16 cores, RAM  768GB, Local storage: 2 * 1 TB, Network 2 x 2 x 10Gbit/s

R430 will be for gridftp and some micro services, R630 will be for re-encryption and some micro services.

Physical installation done, networking in planning. No OS or SW installed yet.

**Comment by jhagberg** [comment]
@jaakkocsc 
any updates on Network? Do you utilize both 10G links?
