### ISSUE TITLE
Investigate/implement low-level monitoring of instances/services status

### ISSUE THREAD

**Issue by dtitov** [NBISweden/LocalEGA#205]
Gather info for ELK not only from Python loggers, but also from some other low-level source (like syslog) to know about events of instances failures.

**Comment by dtitov** [comment]
Well, I read about this topic today and looks like the `collectd` is something that we might want to use: https://collectd.org/ 

With `collectd` and ELK, we can create cool monitoring and reporting stuff like this: https://clevertap.com/blog/telemetry-with-collectd-logstash-elasticsearch-and-grafana-elg/

But in order to do this, we need to include `collectd` to each of our images. That can be achieved by including it to the `common` image and then extending all our other images from this common one.

**Comment by juhtornr** [comment]
This is no longer relevant because we can monitor the usage from Kubernetes/Openshift/etc and we can leverage logging, Hystrix etc if needed.
