### ISSUE TITLE
Put LocalEGA to Docker images from local resource

### ISSUE THREAD

**Issue by dtitov** [NBISweden/LocalEGA#207]
We need to get rid of 
`RUN pip3.6 install git+https://github.com/NBISweden/LocalEGA.git@${checkout}`

And replace it with something like `ADD` or `COPY` and then pipping from local folder. So that we are no more dependent on a remote resource and are able to bring local changes to the local Docker deployment by simply by rebuilding the image locally.

**Comment by juhtornr** [comment]
This is done by mounting source code to PYTHONPATH in docker-compose.yml (ega.yml) file:

https://github.com/NBISweden/LocalEGA/commit/3c181fd745841bc271cbf82044f1a997e662004f#diff-8c6c1bf5a030b5fadfc257695278f300R203

It was merged in other PR so I suggest that we
