### ISSUE TITLE
Clean history to favor LFS

### ISSUE THREAD

**Issue by silverdaz** [NBISweden/LocalEGA#218]
RPMs and ZIPs are moved to git LFS.
However, the history should be cleaned too.

Note: Requires everything to re-clone the repo.

**Comment by juhtornr** [comment]
Before we can remove files and rewrite the repository history we need to commit and push all our local changes to the repo.

About rewriting the history there's several possibilities:

https://stackoverflow.com/a/646694

I suggest that choose option #5.

**Comment by viklund** [comment]
```bash
#!/usr/bin/env bash

## Clone it
git clone git@github.com:NBISweden/LocalEGA.git LocalEGA-cleaning
cd LocalEGA-cleaning

## Checkout all branches locally
git branch -r | grep -v HEAD | grep origin | cut -d/ -f 2- | xargs -i git checkout {}

## Filter stuff
git filter-branch --index-filter 'git rm --cached --ignore-unmatch extras/rpmbuild/RPMS/x86_64/*rpm extras/rpmbuild/SOURCES/*bz2{,.sig} docker/images/worker/rpmbuild/SOURCES/*bz2{,.sig}' --tag-name-filter cat -- --all

## Push it
#git push --all --tags```

**Comment by silverdaz** [comment]
It seems that some part of the history is missing. Namely, the earlier part of Java. That gets the repo confused and it thinks it is forked from the CSCfi/LocalEGA repo, which contains only the Java part.

Juha is going to remove the CSCfi/LocalEGA repo. Let's see how github adapts.

**Comment by viklund** [comment]
The Java parts were never missing, they're behind the tag `java-version`.

We have two roots in this project. One is the java code, and the other is the python code.

**Comment by silverdaz** [comment]
ok. Fine with me.

But here is why I might have got confused: 
![screen shot 2018-01-17 at 10 07 25](https://user-images.githubusercontent.com/465385/35034451-85cbbd5c-fb6e-11e7-97d8-0437b7f4a07e.png)

You see that disconnection between CSCfi and NBISweden?

**Comment by viklund** [comment]
Yes, the network graph don't show things behind tags. We could add a branch for the old java-version, and then it would show up there somehow, but I don't really see a point with that.
