### ISSUE TITLE
Split ega.yml into several ones: one per LocalEGA instance

### ISSUE THREAD

**Issue by silverdaz** [NBISweden/LocalEGA#239]
It would be nice to have the docker containers of a given LocalEGA instance all on the same network, but on a different network than the other instances.

Moreover, we could try to create separate `.yml` docker-compose files: one per instance.

Our fake CentralEGA would also have its own network and its own `.yml` docker-compose file.

**Comment by blankdots** [comment]
Splitting into different networks id definitely possible:
* as done in these commits: https://github.com/blankdots/LocalEGA/commit/7fa18a3f7e4c3a2266257d5d19ce8005313f0d6b and https://github.com/NBISweden/LocalEGA/commit/c8e96ce2b3981b4fc5ee39f7248921186bc9187a
Note:  running them on the same host might pose problems with the `bridge` device on macOS as  @silverdaz pointed and explained here: https://docs.docker.com/docker-for-mac/networking/#there-is-no-docker0-bridge-on-macos

Looking a bit also into https://docs.docker.com/compose/compose-file/compose-file-v2/#aliases and changing names
