### ISSUE TITLE
Storage + DB 

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/LocalEGA#25]
Submission ID + the rest.

**Comment by silverdaz** [comment]
The database setup is done in #26.

Here I'm only setting the database schema, and some python connection to it.
Therefore, I stick to some simple sqlite3 db for the moment.

The code should be agnostic to the database backend, and
the config settings should be updated to reflect where to connect.

**Comment by silverdaz** [comment]
Using SQLAlchemy now, so the backend doesn't matter.
We can use sqlite, mysql, postgres, etc... with the same code.

The config setting says `database = postgresql+psycopg2://<user>:<password>@<host>:5432`
or `database = sqlite:///lega.db`

**Comment by silverdaz** [comment]
The database backend is changed to Postgres only, because there is a good async driver for it.
