### ISSUE TITLE
Test ingestion on big DemoData

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/LocalEGA#27]
400 Gb

**Comment by silverdaz** [comment]
Tool scripts in the repo now, to help setting up the pipeline

**Comment by nanjiangshu** [comment]
Tested with two files of size 100GB of each. Files are successfully processed and moved to the archive `vault`. However, there is a small error message which shows `integer out of range` when write the record in the postgrel database. A new issue will be opened for debugging of this.
