### ISSUE TITLE
Make re-encryption module support BZip2

### ISSUE THREAD

**Issue by dtitov** [NBISweden/LocalEGA#279]
```
ingest-swe1_1         | [  crypto  ][DEBUG ] (L250) Calculated digest: e4755f4bb9117df1ca9d07f7952416f1
ingest-swe1_1         | [  crypto  ][DEBUG ] (L251) Compared to digest: 108702b6e841bb8a8c17a5a262130c41
```
for ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00458/alignment/HG00458.unmapped.ILLUMINA.bwa.CHS.low_coverage.20130415.bam

**Comment by dtitov** [comment]
Reassigning to @silverdaz

**Comment by dtitov** [comment]
Decryption fails if either "Twofish" encryption algorithm or "BZip2" compression algorithm is used.

**Comment by silverdaz** [comment]
I think that the BZip2 is maybe just a matter of settings, no biggy.
For the Twofish, indeed, this is not implemented. We are not supporting the full OpenPGP standard.

**Comment by silverdaz** [comment]
Closing this issue since we favored Crypt4GH
