### ISSUE TITLE
Connect Scheduler and Worker

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/LocalEGA#30]

**Comment by silverdaz** [comment]
# Scheduler and Worker are now connected.

The scheduler exposes a very simple endpoint now, called `ingest`.
We should POST data to it, as a base64-encoded string.
After decoding, it is a JSON-formatted content with:
* submission_id
* user_id (to find its inbox)
* a list of files, where each file is of the form:
  * filename
  * encrypted hash (the value, not a filepath to it)
  * unencrypted hash (idem
  * hash algorithm (default: md5, but in case we support others)

The scheduler determines the inbox from the user_id, and checks that the encrypted files exist and conform to their checksums. If this goes fine, we copy the file into a staging area (which is constructed using the submission id), and we send a message to the broker containing the path to the file in the staging area, the original hash value, and where to put the re-encrypted version.

---- 
A worker listens to the `jobs` queue in the message broker and picks _one_ when it arrives.
It (gpg-)decrypts the file, checks its integrity with the hash value and re-encrypts it (in memory) using AES256 and a strong RSA key.

We can start several workers.

**Issues:** I have trouble to connect the workers to the gpg-agent, so they retrieve the passphrase. Passing the passphrase when calling the decrypt function doesn't seem to work (as advertised in the doc). When I input the passphrase by hand, re-encryption works fine.

When done, the worker only puts a message in the `finished` queue. 
In case of errors, the message does not go to `finished`. It goes instead to `errors`, and nothing more

----

A vault service listens to the `finished` queue and moves to file from the staging area into the vault.
Status: Not implemented yet, and not part of this issue 😛 

----

We should maybe have a monitor service that listens to the `errors` queue and more.
 
---- 

## Not done yet
* Lots of error checking and log messages
* Database coupling for progress tracking (Note: possible implementation using the MQ itself, but it might be complicated)

**Comment by silverdaz** [comment]
The message broker drops the connection after the encryption.

It seems that it is a long running task for some large file, and the message broker thinks the connection is idle and drops it.

Solution 1: Turn off that feature in the broker (called heartbeat)
Solution 2: Account for it with some custom code
Solution 3: Another architecture (maybe even without broker!)

**Comment by silverdaz** [comment]
The chosen solution for the moment is to turn the heartbeat off.

Something is bothering me with that solution (or maybe this architecture). Something seems strange. That'll do it for the moment.
I'm thinking about another solution in the back of my mind, though.
