### ISSUE TITLE
Key-server doesn't support encryption subkeys of PGP key

### ISSUE THREAD

**Issue by dtitov** [NBISweden/LocalEGA#323]
To learn more: https://davesteele.github.io/gpg/2014/09/20/anatomy-of-a-gpg-key/

Users may have PGP keys with subkeys. I believe that we should support this in LocalEGA as it's not something very rare and might be a quite common use-case, as for me. And it should be pretty simple to implement anyway. 

@blankdots, I'm assigning this to you, if you don't mind. We don't have to fix it right away, but we should keep an eye on this and maybe plan it for a next sprint.

**Comment by dtitov** [comment]
As a temporary solution, I use only one key with `public static final int RSA_GENERAL = 1;       // RSA (Encrypt or Sign)` type and it works. But I believe we should add support for composite keys in the future.

**Comment by silverdaz** [comment]
For the moment, it's correct, the lega-cryptor package doesn't support subkeys.
We didn't need them to test our simple settings.

It is on the todo-list to support more features, once the rest is in place.

**Comment by juhtornr** [comment]
@dtitov @silverdaz I assume that this is not valid anymore so I'll close this
