### ISSUE TITLE
remove nc and curl dependency for the broker

### ISSUE THREAD

**Issue by silverdaz** [NBISweden/LocalEGA#327]
.... and get a faster boot

**Comment by blankdots** [comment]
This has been done in Kubernetes deployment: https://github.com/NBISweden/LocalEGA/blob/dev/deployments/kube/auto/scripts/mq.sh#L76-L81

by using a combination of https://www.rabbitmq.com/rabbitmqctl.8.html#wait and the right directory for the PID file and using https://www.rabbitmq.com/management-cli.html importing configuration files
