### ISSUE TITLE
Vault skel ingestion

### ISSUE THREAD

**Issue by silverdaz** [NBISweden/LocalEGA#42]
Create a service that moves the re-encrypted files from the staging area into the vault

**Comment by silverdaz** [comment]
The vault listener moves files from the staging area into the vault.

Note: the vault is just some folder on my machine at the moment, fully configurable by the config files.

**Comment by jhagberg** [comment]
Can you provide more information here?

**Comment by silverdaz** [comment]
Not really here. I just pick the message from the "completed" queue and move the file it mentions into another location. 

I should update the database and notify CentralEGA upon completion. 

So at the moment, it's just rudimentary
