### ISSUE TITLE
Setup host machines to install and test the inbox and the worker components

### ISSUE THREAD

**Issue by nanjiangshu** [NBISweden/LocalEGA#54]

**Comment by nanjiangshu** [comment]
I have started a virtual machine on SSC and managed to install sftp-inbox on it. Test is passed and the sftp-server can be accessed both from the localhost and remotely. The README file has been updated for the full installation.

**Comment by nanjiangshu** [comment]
The front-end for the users to register an account for the sftp-inbox server is lacking

**Comment by silverdaz** [comment]
I'll handle the front-end. 

It'll probably be a ReST call from Central EGA and a JSON response

**Comment by silverdaz** [comment]
The code is updated in the `dev` branch with some scripts and descriptions to start the different components involved in the LocalEGA pipeline.

This should help Nanjiang with the setup.
