### ISSUE TITLE
Buy Hardware or contract of cloud resources

### ISSUE THREAD

**Issue by silverdaz** [NBISweden/LocalEGA#62]
For the vault filesystem, Oscar asked the sys-admins at CRG.
They forwarded [this document](https://www.bsc.es/support/MareNostrum3-ug.pdf)

Under section 4.2, there is information about GPFS (IBM General Parallel File System)

**Comment by jhagberg** [comment]
asked price from UDC frame agreement in Uppsala. waiting for an estimate so we can request a budget.

**Comment by jhagberg** [comment]
We are going to test on SUNET cloud.
